# # This is a basic workflow to help you get started with Actions
# name: auto-deploy
# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the main branch
# on:
#   push:
#     branches: [develop]    <- 마스터 브랜치에 push가 발생할 경우 아래 jobs 실행
#   pull_request:
#     branches: [develop]
# jobs:
#   build:
#     name: API Server Build and Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: executing remote ssh commands using private key
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: ${{ secrets.PORT }}
#           key: ${{ secrets.PRIVATEKEY }}
#           script: | 
#             cd next-js
#             git checkout develop
#             git pull origin develop
#             npm install
#             npm run start